# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Continuous Delivery

on:
  push:
    branches: 
      - main 


jobs:
  delivery:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v4
    
      - name: Simulando CD
        uses: actions/upload-artifact@v4
        with:
          name: zipped-project.zip
          path: |
            Program.cs
  
  deploy: 
   runs-on:  ubuntu-latest
   needs: delivery
   steps:
    - uses: actions/download-artifact@v4
      with:
        name: zipped-project.zip
    - name: Display structure of downloaded files
      run: ls -R