# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .Release Pipeline

on:
  workflow_call:  
  push:
    branches: [ "dev" ]


jobs:
  dotnet-build:
    name: BUILD
    uses: ./.github/workflows/dotnetbuild.yml

  code-ql:
    name: SCAN
    needs: dotnet-build
    uses: ./.github/workflows/codeQl.yml

